name: Generate Pacman Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Pacman GitHub Contribution Graph
        uses: jaywcjlove/github-action-package@main
        with:
          theme: pacman
          target_branch: pacman-output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
