name: Generate Pacman Animation

on:
  schedule:
    # بيشتغل تلقائياً كل 24 ساعة
    - cron: "0 0 * * *"
  
  # بيسمحلك تشغليه بإيدك في أي وقت
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # بيسحب ملفات الريبو
      - uses: actions/checkout@v3
      
      # الأكشن السحري المخصص لباكمان فقط!
      - name: Generate Pacman Graph
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Basmala194
          template: classic
          base: ""
          # تفعيل جراف باكمان
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          config_order: isocalendar
          # السطر ده بيجبر الأداة تستخدم تصميم باكمان
          plugin_isocalendar_theme: pacman
